export const defaultCategories = [
  { id: "c1", name: "Ăn uống", type: "expense" },
  { id: "c2", name: "Đi lại", type: "expense" },
  { id: "c3", name: "Học tập", type: "expense" },
  { id: "c4", name: "Giải trí", type: "expense" },
  { id: "c5", name: "Sinh hoạt", type: "expense" },
  { id: "c6", name: "Sức khỏe", type: "expense" },
  { id: "c7", name: "Lương", type: "income" },
  { id: "c8", name: "Thưởng", type: "income" },
  { id: "c9", name: "Làm thêm", type: "income" },
  { id: "c10", name: "Khác", type: "both" },
];

export const defaultTransactions = [
  {
    id: "t1",
    title: "Lương part-time",
    amount: 3500000,
    type: "income",
    categoryId: "c9",
    date: "2026-02-05",
    note: "Nhận lương ca tối tháng 2",
  },
  {
    id: "t2",
    title: "Mua giáo trình mobile",
    amount: 240000,
    type: "expense",
    categoryId: "c3",
    date: "2026-02-11",
    note: "Tài liệu cho đồ án cuối kỳ",
  },
  {
    id: "t3",
    title: "Tiền trọ",
    amount: 1200000,
    type: "expense",
    categoryId: "c5",
    date: "2026-02-15",
    note: "Thanh toán đầu tháng",
  },
  {
    id: "t4",
    title: "Lương part-time",
    amount: 3600000,
    type: "income",
    categoryId: "c9",
    date: "2026-03-05",
    note: "Ca làm thêm tháng 3",
  },
  {
    id: "t5",
    title: "Ăn trưa cả tuần",
    amount: 420000,
    type: "expense",
    categoryId: "c1",
    date: "2026-03-08",
    note: "Chi phí ăn uống trong tuần",
  },
  {
    id: "t6",
    title: "Đổ xăng",
    amount: 150000,
    type: "expense",
    categoryId: "c2",
    date: "2026-03-12",
    note: "",
  },
  {
    id: "t7",
    title: "Thưởng dự án nhóm",
    amount: 800000,
    type: "income",
    categoryId: "c8",
    date: "2026-03-21",
    note: "Thưởng hoàn thành demo React Native",
  },
  {
    id: "t8",
    title: "Mua tai nghe",
    amount: 680000,
    type: "expense",
    categoryId: "c4",
    date: "2026-03-24",
    note: "Thiết bị phục vụ học online",
  },
  {
    id: "t9",
    title: "Lương thực tập",
    amount: 5200000,
    type: "income",
    categoryId: "c7",
    date: "2026-04-05",
    note: "Lương chính thức kỳ thực tập",
  },
  {
    id: "t10",
    title: "Tiền điện nước",
    amount: 430000,
    type: "expense",
    categoryId: "c5",
    date: "2026-04-10",
    note: "",
  },
  {
    id: "t11",
    title: "Khám răng",
    amount: 350000,
    type: "expense",
    categoryId: "c6",
    date: "2026-04-18",
    note: "Khám định kỳ",
  },
  {
    id: "t12",
    title: "Freelance UI",
    amount: 1500000,
    type: "income",
    categoryId: "c10",
    date: "2026-04-22",
    note: "Thiết kế giao diện cho CLB",
  },
  {
    id: "t13",
    title: "Mua đồ ăn tối",
    amount: 180000,
    type: "expense",
    categoryId: "c1",
    date: "2026-05-02",
    note: "",
  },
  {
    id: "t14",
    title: "Lương thực tập",
    amount: 5200000,
    type: "income",
    categoryId: "c7",
    date: "2026-05-05",
    note: "Kỳ lương tháng 5",
  },
  {
    id: "t15",
    title: "Đóng tiền trọ",
    amount: 1200000,
    type: "expense",
    categoryId: "c5",
    date: "2026-05-06",
    note: "Tiền phòng tháng 5",
  },
  {
    id: "t16",
    title: "Mua giáo trình",
    amount: 240000,
    type: "expense",
    categoryId: "c3",
    date: "2026-05-07",
    note: "Tài liệu môn mobile",
  },
  {
    id: "t17",
    title: "Cà phê họp nhóm",
    amount: 95000,
    type: "expense",
    categoryId: "c1",
    date: "2026-05-08",
    note: "Chuẩn bị báo cáo cuối kỳ",
  },
  {
    id: "t18",
    title: "Xe buýt tháng",
    amount: 200000,
    type: "expense",
    categoryId: "c2",
    date: "2026-05-09",
    note: "Đi học và đi thực tập",
  },
  {
    id: "t19",
    title: "Thưởng chuyên cần",
    amount: 700000,
    type: "income",
    categoryId: "c8",
    date: "2026-05-10",
    note: "",
  },
  {
    id: "t20",
    title: "Khám sức khỏe",
    amount: 300000,
    type: "expense",
    categoryId: "c6",
    date: "2026-05-11",
    note: "Khám theo lịch công ty",
  },
];

export const defaultBudgets = [
  { id: "b1", categoryId: "c1", limit: 1800000, month: "2026-05" },
  { id: "b2", categoryId: "c2", limit: 500000, month: "2026-05" },
  { id: "b3", categoryId: "c3", limit: 600000, month: "2026-05" },
  { id: "b4", categoryId: "c5", limit: 1500000, month: "2026-05" },
  { id: "b5", categoryId: "c6", limit: 400000, month: "2026-05" },
];
